services:
  aria_dev:
    build: 
      context: . 
      dockerfile: Dockerfile-complete-untested
    container_name: aria_dev
    network_mode: "host"
    privileged: true   
    group_add:
      - plugdev
      - video
      - dialout
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - UDEV=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
    volumes:
      - /media/cvg/T7 Shield1/spot-aria-recordings:/bags  
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/run/udev:/run/udev:ro"
      - "/dev/bus/usb:/dev/bus/usb:ro"
      - "/dev/serial/by-id:/dev/serial/by-id"
      - "/dev:/dev"
    stdin_open: true
    tty: true

