version: "3.8"
services:
  imu_ros:
    build: .
    container_name: spot_aria_gripper_recorder
    network_mode: "host"  # Allows ROS to work with host networking
    privileged: true      # Grants USB device access
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Adjust based on your IMU port
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1
    volumes:
      - /media/cvg/T7 Shield/spot-aria-recordings:/bags  
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: ["gpu"]
    #command: bash -c "source /catkin_ws/devel/setup.bash"
